config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  authenticated do
    root to: "welcome#index", as: :authenticated_root
  end

  get 'welcome/index'

  get 'articles/my_articles', to: 'articles#my_articles'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {maximum: 50}
  validates :text, presence: true, length: {maximum: 3000}
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user, optional: true
  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 1, maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @writer = User.find(@article.user_id)
  end

  def new
    # @article = Article.new(article_params)
    @article = current_user.articles.new
  end

  def edit
    @article = Article.find(params[:id])
    if current_user.id != @article.user_id
      redirect_to(article_path(@article), :flash => {:alert => "Only author can edit this article."})
    end
  end

  def create
    # Show the params value
    # render plain: params[:article].inspect

    # @article = Article.new(article_params)
    @article = current_user.articles.new(article_params)
    if @article.save
      # redirect to show action
      # redirect_to(@article) is equal to redirect_to(article_path(@article))
      redirect_to(@article, notice: 'Article created.')
    else
      redirect_to(new_article_path, flash: { new_article_errors: @article.errors.full_messages })
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to(@article, notice: 'Article edited.')
    else
      render('edit')
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
      # redirect_to(articles_path, flash: { delete_article_errors: @article.errors.full_messages })
    @article.destroy
    redirect_to(articles_path, notice: 'Article deleted.')
    else
  end

  def my_articles
    @my_articles = current_user.articles.all
  end


  private
    def article_params
      params.require(:article).permit(:title,:text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    if @comment.save
      redirect_to(article_path(@article))
    else
      redirect_to(article_path(@article), flash: { comment_errors: @comment.errors.full_messages})
    end
  end

  def destroy
    @article = current_user.articles.find(params[:article_id])
    # @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if current_user.id == @comment.user_id
      @comment.destroy
      redirect_to(article_path(@article), flash: { notice: 'Comment destroyed successfully.'})
    else
      redirect_to(article_path(@article), flash: { alert: 'Only author and owner can delete comments.'})
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:commenter, :body).merge!(user_id: current_user&.id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |form| %>

  <% if flash[:new_article_errors] %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h3>
        <%= pluralize(flash[:new_article_errors].count, "error") %> prohibited
        this article from being saved:
      </h3>
      <ul>
        <% flash[:new_article_errors].each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  <% end %>

  <p>
    <%= form.input :title, :label => 'Title' %>
  </p>

  <p>
    <%= form.input :text, as: :ckeditor, input_html: {ckeditor: {toolbar: 'mini'}} %>
  </p>


  <%= form.button :submit, class: "btn btn-primary" %>


<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>
<br />

<%= link_to(articles_path) do %>
  <button type="button" class="btn btn-info">Back</button>
<% end %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <h1>Listing All Articles</h1>
  </div>

  <% @articles.reverse_each do |article| %>
    <div class="row">
      <div class="article-show">
        <div class="media">
          <div class="media-body">
            <%= link_to(article_path(article)) do %>
              <h5 class="mt-0"><%= article.title %></h5>
            <% end %>
            <%= article.text.html_safe %>
          </div>
        </div>
        <hr/>
        <div class="article-details">
          <p><strong>Author: </strong><%= User.find(article.user_id).email %></p>
          <i><small><%= article.created_at.strftime("%d/%m/%y") %></small></i>
        </div>
      </div>
    </div>
  <% end %>


</div>
</div>

app/views/articles/my_articles.html.erb
<div class="container">
  <div class="row">
    <h1>My Articles</h1>
  </div>
  <div class="row">
    <table class="table table-dark">
      <thead class="thead-dark">
      <tr>
        <th scope="col">Date created</th>
        <th scope="col">Title</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
      </thead>
      <tbody>
      <% @my_articles.each do |article|  %>
        <tr>
          <th scope="row"><%= article.created_at%></th>
          <td><%= article.title %></td>
          <td><%= link_to('Show',article_path(article)) %></td>
          <td><%= link_to('Edit', edit_article_path(article)) %></td>
          <td><%= link_to('Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'})  %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/articles/new.html.erb
<h1>Create New Article</h1>
<%= render 'form' %>
<br />
<%= link_to(articles_path) do %>
  <button type="button" class="btn btn-info">Back</button>
<% end %>

app/views/articles/show.html.erb
<p>
  <h3><strong>Title:</strong></h3>
  <%= @article.title %>
</p>
<hr />
<p>
  <h3><strong>Text:</strong></h3>
  <%= @article.text.html_safe %>
</p>
<hr />
<p>
  <h3><strong>Create at:</strong></h3>
  <%= @article.created_at %>
</p>
<hr />
<p>
  <h3><strong>Author:</strong></h3>
  <%= @writer.email %>
</p>
<hr />
<br />
<h2>Comments:</h2>
<% if @article.comments.length != 0%>
  <%= render @article.comments %>
<% else %>
  <p>No comments.</p>
<% end %>

<hr />
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<% if user_signed_in? and current_user.id == @article.user_id %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class="media comment">

  <div class="media-body">
    <h5 class="mt-0"><%= comment.commenter %> <small><i><%= comment.created_at.strftime("%d/%m/%y") %></i></small></h5>
    <%= simple_format comment.body %>
  </div>
  <div class="media-right media-top">
    <% if user_signed_in? and (current_user.id == @article.user_id or current_user.id == comment.user_id) %>
      <p>
        <%= link_to([comment.article, comment],
                    method: :delete,
                    data: {confirm: 'Are you sure?'}) do%>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@article, @article.comments.build] do |form| %>
  <% if flash[:comment_errors]%>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h3>
        <%= pluralize(flash[:comment_errors].count, "error") %> prohibited
        this comment from being created:
      </h3>
      <ul>
        <% flash[:comment_errors].each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.input :commenter, label: 'Commenter', input_html: {value: current_user&.email} %>
  </p>
  <p>
    <%= form.input :body, as: :text, label: 'Body', input_html: {maxlength: 500, rows: 5} %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
</head>

<body>
  <% if notice %>
    <div class="alert alert-info">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

  <% end %>
  <% if alert %>
    <p class="alert alert-warning">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </p>
  <% end %>
  <header class="navbar  navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to (root_path), class: 'navbar-brand' do %>
          EASY_BLOG!
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'articles' and params[:action] == 'index'%>">
          <%= link_to("All Articles", articles_path) %>
        </li>
        <% if user_signed_in? %>
          <li class="<%= 'active' if params[:controller] == 'articles' and params[:action] == 'my_articles'%>">
            <%= link_to("My Articles", articles_my_articles_path) %>
          </li>
          <li class="<%= 'active' if params[:controller] == 'articles' and params[:action] == 'new'%>">
            <%= link_to("New Article", new_article_path) %>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to(edit_user_registration_path) do%>
              <span class="glyphicon glyphicon-user"></span>

              My Profile
            <% end %>
          </li>
          <li>
            <%= link_to(destroy_user_session_path, method: :delete) do%>
              <span class="glyphicon glyphicon-log-out"></span>
              Logout
            <% end %>
          </li>
        <% else %>
          <li><%= link_to(new_user_session_path) do %>
                <span class="glyphicon glyphicon-log-in"></span> Login
              <% end %>
          </li>
          <li>
            <%= link_to(new_user_registration_path) do%>
              <span class="glyphicon glyphicon-user"></span> Sign Up
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

  </header>
<div id="main-container" class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <H1>This is an EASY_BLOG!</H1>
    <p>
      This is an EASY_BLOG!. Follow these steps to be part of us.
    </p>
    <ol>
      <li>Click Sign Up button</li>
      <li>Enter your email and password and click 'SignUp'.</li>
      <li>Click 'Create Article' to create new article</li>
      <li>Click 'All Articles' to see all other articles from other users</li>
      <li>Click 'My Articles' to see all of your published articles</li>
      <li>Hoorey! You are now part of us.</li>
    </ol>
  </div>
</div>